# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_upload5.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'file_upload5.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_upload5.proto\x12\x06upload\"\x87\x01\n\x12\x46ileUploadRequest1\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12*\n\tmeta_data\x18\x02 \x01(\x0b\x32\x15.upload.FileMetaData1H\x00\x12\x14\n\nchunk_data\x18\x03 \x01(\x0cH\x00\x12\x14\n\nend_signal\x18\x04 \x01(\x08H\x00\x42\x06\n\x04\x64\x61ta\"J\n\rFileMetaData1\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0f\n\x07\x66ile_id\x18\x02 \x01(\x05\x12\x15\n\rdata_category\x18\x03 \x01(\t\"M\n\x13\x46ileUploadResponse1\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0c\x63hunk_number\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_upload5_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEUPLOADREQUEST1']._serialized_start=31
  _globals['_FILEUPLOADREQUEST1']._serialized_end=166
  _globals['_FILEMETADATA1']._serialized_start=168
  _globals['_FILEMETADATA1']._serialized_end=242
  _globals['_FILEUPLOADRESPONSE1']._serialized_start=244
  _globals['_FILEUPLOADRESPONSE1']._serialized_end=321
# @@protoc_insertion_point(module_scope)
