# Generated by Django 5.1.7 on 2025-05-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_landpreparation_rbghcompartmenttracker_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rbghcompartmenttracker',
            options={'managed': False},
        ),
    ]
