# Generated by Django 5.1.7 on 2025-05-06 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_rbghcompartmenttracker_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandPreparation',
        ),
        migrations.AlterModelTable(
            name='rbghcompartmenttracker',
            table='RBGH_Compartment_Tracker',
        ),
    ]
