# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.contrib.gis.db import models


class LandPreparation(models.Model):
    date_of_qc = models.DateTimeField(blank=True, null=True)
    works_order_number = models.FloatField(blank=True, null=True)
    start_date_of_activity = models.DateTimeField(blank=True, null=True)
    end_date_of_activity = models.DateTimeField(blank=True, null=True)
    qc_attempt = models.FloatField(blank=True, null=True)
    compartment_id = models.TextField(blank=True, null=True)
    qc_plot_id = models.TextField(blank=True, null=True)
    number_of_planted_trees = models.FloatField(blank=True, null=True)
    number_of_pits = models.FloatField(blank=True, null=True)
    number_of_pits_unfirmed_tilth = models.FloatField(blank=True, null=True)
    number_of_pits_opened_to_1m = models.FloatField(blank=True, null=True)
    number_of_pits_niche_depth_ge_25cm = models.FloatField(blank=True, null=True)
    number_of_pits_niche_width_ge_30cm = models.FloatField(blank=True, null=True)
    number_of_invasive_trees_felled = models.FloatField(blank=True, null=True)
    number_of_standing_invasive_trees = models.FloatField(blank=True, null=True)
    number_of_invasive_trees_stump_height_le_15cm = models.FloatField(blank=True, null=True)
    number_of_stumps = models.FloatField(blank=True, null=True)
    number_of_stumps_affected_by_poison = models.FloatField(blank=True, null=True)
    number_of_stumps_not_affected_by_poison = models.FloatField(blank=True, null=True)
    work_quantity_ha = models.FloatField(blank=True, null=True)
    work_quantity_m = models.FloatField(blank=True, null=True)
    area_qced_ha = models.FloatField(blank=True, null=True)
    spacing_width = models.FloatField(blank=True, null=True)
    spacing_length = models.FloatField(blank=True, null=True)
    marking_and_pitting_correct_spacing = models.TextField(blank=True, null=True)
    weeds_treated_percentage = models.TextField(blank=True, null=True)
    herbicide_effectivity = models.TextField(blank=True, null=True)
    coordinate_latitude = models.FloatField(blank=True, null=True)
    coordinate_longitude = models.FloatField(blank=True, null=True)
    coordinate_altitude = models.FloatField(blank=True, null=True)
    coordinate_precision = models.FloatField(blank=True, null=True)
    forester = models.TextField(blank=True, null=True)
    supervisor = models.TextField(blank=True, null=True)
    team_leader = models.TextField(blank=True, null=True)
    team_type = models.TextField(blank=True, null=True)
    team = models.TextField(blank=True, null=True)
    activity = models.TextField(blank=True, null=True)
    land_cover = models.TextField(blank=True, null=True)
    qc_reporter = models.TextField(blank=True, null=True)
    coordinate = models.TextField(blank=True, null=True)
    slashing_bush_clearing_completeness = models.TextField(blank=True, null=True)
    slash_bush_clearance_height = models.TextField(blank=True, null=True)
    rows_at_90_degrees_to_road = models.TextField(blank=True, null=True)
    large_debris_stones_removed = models.TextField(blank=True, null=True)
    invasive_trees_lopped_correctly = models.TextField(blank=True, null=True)
    slashed_trees_removed_from_smz_asi = models.TextField(blank=True, null=True)
    circles_not_meeting_05m_radius = models.FloatField(blank=True, null=True)
    weeds_within_05m_radius_circle = models.FloatField(blank=True, null=True)
    line_clearing_2m_width_conformance = models.TextField(blank=True, null=True)
    unslashed_indigenous_trees_dbh_gt_5cm = models.FloatField(blank=True, null=True)
    slashed_trees_dbh_gt_5cm = models.FloatField(blank=True, null=True)
    native_trees_vines_cleared = models.FloatField(blank=True, null=True)
    native_trees_vines_incomplete_clearance = models.FloatField(blank=True, null=True)
    invasive_species_unslashed_stems = models.FloatField(blank=True, null=True)
    comments = models.TextField(blank=True, null=True)
    photo_east = models.TextField(blank=True, null=True)
    photo_west = models.TextField(blank=True, null=True)
    photo_south = models.TextField(blank=True, null=True)
    photo_north = models.TextField(blank=True, null=True)
    field_id = models.BigIntegerField(db_column='_id', blank=True, null=True)  # Field renamed because it started with '_'.
    field_uuid = models.TextField(db_column='_uuid', blank=True, null=True)  # Field renamed because it started with '_'.
    field_submission_time = models.DateTimeField(db_column='_submission_time', blank=True, null=True)  # Field renamed because it started with '_'.
    field_validation_status = models.TextField(db_column='_validation_status', blank=True, null=True)  # Field renamed because it started with '_'.
    field_submitted_by = models.TextField(db_column='_submitted_by', blank=True, null=True)  # Field renamed because it started with '_'.
    slashing_accuracy = models.FloatField(blank=True, null=True)
    bush_clearing_accuracy = models.FloatField(blank=True, null=True)
    slashing_height_accuracy = models.FloatField(blank=True, null=True)
    bush_clearing_height_accuracy = models.FloatField(blank=True, null=True)
    slashed_weeds_control_accuracy = models.TextField(blank=True, null=True)
    bush_clearing_weeds_control_accuracy = models.TextField(blank=True, null=True)
    average_slashing_accuracy = models.FloatField(blank=True, null=True)
    average_bush_clearing_accuracy = models.FloatField(blank=True, null=True)
    firm_soil_tilth = models.FloatField(blank=True, null=True)
    niche_depth_accuracy = models.FloatField(blank=True, null=True)
    percentage_correct_spacing = models.FloatField(blank=True, null=True)
    pegging_accuracy = models.FloatField(blank=True, null=True)
    circle_weeding_accuracy = models.TextField(blank=True, null=True)
    stump_poisoning_effectively = models.FloatField(blank=True, null=True)
    vine_clearance_completeness = models.FloatField(blank=True, null=True)
    tree_preservation = models.FloatField(blank=True, null=True)
    liana_cutting_maintenance_accuracy = models.FloatField(blank=True, null=True)
    liana_cutting_establishment_accuracy = models.FloatField(blank=True, null=True)
    weeds_control_accuracy = models.TextField(blank=True, null=True)
    ring_weeding_accuracy = models.TextField(blank=True, null=True)
    felling = models.FloatField(blank=True, null=True)
    stump_height_conformance = models.FloatField(blank=True, null=True)
    felling_and_lopping_accuracy = models.FloatField(blank=True, null=True)
    pre_plant_spraying = models.FloatField(blank=True, null=True)
    soil_covered_quality = models.TextField(blank=True, null=True)
    slots_quality = models.TextField(blank=True, null=True)
    slot_slope_quality = models.TextField(blank=True, null=True)
    fertilizer_accuracy = models.TextField(blank=True, null=True)
    qc_result = models.FloatField(blank=True, null=True)
    qc_result_pass_or_fail = models.TextField(blank=True, null=True)
    geometry = models.PointField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'land_preparation'
