# Generated by Django 5.1.7 on 2025-05-02 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documentuploads/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('date_captured', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='GeospatialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_dir', models.CharField(default='No File Dir', max_length=100)),
                ('tiles_path', models.CharField(blank=True, max_length=100, null=True)),
                ('data_type', models.CharField(max_length=100)),
                ('type_of_data', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_captured', models.DateField()),
                ('tiles_generated', models.BooleanField(default=False)),
                ('thumbnails_dir', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mapuploads/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('date_captured', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysispData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='analysisuploads/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('date_captured', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('document_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.documentdata')),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_analysis_data', to='upload.geospatialdata')),
                ('output_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_analysis_data', to='upload.geospatialdata')),
                ('map_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.mapdata')),
            ],
        ),
    ]
