# Generated by Django 5.1.7 on 2025-05-08 16:15

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('email', models.EmailField(default='kojo@gmail.com', max_length=100, unique=True)),
                ('password', models.CharField(default='No Password', max_length=100)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.departments')),
                ('role', models.ManyToManyField(blank=True, to='upload.role')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documentuploads/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('date_captured', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('desc_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.departmentstaff')),
            ],
        ),
        migrations.CreateModel(
            name='GeospatialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_dir', models.CharField(default='No File Dir', max_length=100)),
                ('tiles_path', models.CharField(blank=True, max_length=100, null=True)),
                ('data_type', models.CharField(max_length=100)),
                ('type_of_data', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_captured', models.DateField()),
                ('tiles_generated', models.BooleanField(default=False)),
                ('thumbnails_dir', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.departmentstaff')),
            ],
        ),
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mapuploads/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('date_captured', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('desc_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.departmentstaff')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysispData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='analysisuploads/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('date_captured', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('desc_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.departmentstaff')),
                ('document_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.documentdata')),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_analysis_data', to='upload.geospatialdata')),
                ('output_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_analysis_data', to='upload.geospatialdata')),
                ('map_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.mapdata')),
            ],
        ),
        migrations.AddIndex(
            model_name='documentdata',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['desc_embedding'], m=16, name='documentdata_desc_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='geospatialdata',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['desc_embedding'], m=16, name='geospatial_desc_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='mapdata',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['desc_embedding'], m=16, name='mapdata_desc_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='analysispdata',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['desc_embedding'], m=16, name='analysisdata_desc_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
