# Generated by Django 5.1.7 on 2025-03-23 16:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeospatialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='geotiffs/')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326)),
                ('data_type', models.CharField(max_length=100)),
                ('type_of_data', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_captured', models.DateField()),
                ('tiles_generated', models.BooleanField(default=False)),
            ],
        ),
    ]
