# Generated by Django 5.1.7 on 2025-05-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapdata',
            old_name='file',
            new_name='file1',
        ),
    ]
