# Generated by Django 5.1.7 on 2025-03-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geospatialdata',
            name='raster',
        ),
    ]
