# Generated by Django 5.1.7 on 2025-03-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_geospatialdata_raster'),
    ]

    operations = [
        migrations.AddField(
            model_name='geospatialdata',
            name='tile_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
