# Generated by Django 5.1.7 on 2025-04-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_analysispdata_thumbnail_documentdata_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geospatialdata',
            name='file',
        ),
        migrations.RemoveField(
            model_name='geospatialdata',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='geospatialdata',
            name='tile_path',
        ),
        migrations.AddField(
            model_name='geospatialdata',
            name='files_dir',
            field=models.CharField(default='No File Dir', max_length=100),
        ),
        migrations.AddField(
            model_name='geospatialdata',
            name='thumbnails_dir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='geospatialdata',
            name='tiles_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
