# Generated by Django 5.1.7 on 2025-04-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_departments_role_departmentstaff_analysispdata_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentstaff',
            name='email',
            field=models.EmailField(default='kojo@gmail.com', max_length=100, unique=True),
        ),
    ]
