# Generated by Django 5.1.7 on 2025-04-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_departmentstaff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentstaff',
            name='password',
            field=models.CharField(default='No Password', max_length=100),
        ),
    ]
