# Generated by Django 5.1.7 on 2025-04-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_departmentstaff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentstaff',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
