# Generated by Django 5.1.7 on 2025-04-23 23:09

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_alter_departmentstaff_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysispdata',
            name='description_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='documentdata',
            name='description_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='geospatialdata',
            name='desc_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='mapdata',
            name='description_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddIndex(
            model_name='geospatialdata',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['desc_embedding'], m=16, name='geospatial_desc_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
