# Generated by Django 5.1.7 on 2025-04-26 10:06

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_analysispdata_description_embedding_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysispdata',
            old_name='description_embedding',
            new_name='desc_embedding',
        ),
        migrations.RenameField(
            model_name='documentdata',
            old_name='description_embedding',
            new_name='desc_embedding',
        ),
        migrations.RenameField(
            model_name='mapdata',
            old_name='description_embedding',
            new_name='desc_embedding',
        ),
        migrations.AddIndex(
            model_name='analysispdata',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['desc_embedding'], m=16, name='analysisdata_desc_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='documentdata',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['desc_embedding'], m=16, name='documentdata_desc_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='mapdata',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['desc_embedding'], m=16, name='mapdata_desc_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
